# Generated by Django 4.1.4 on 2022-12-26 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(choices=[(datetime.time(16, 0), '16:00'), (datetime.time(12, 0), '12:00'), (datetime.time(14, 0), '14:00'), (datetime.time(17, 0), '17:00'), (datetime.time(11, 30), '11:30'), (datetime.time(10, 30), '10:30'), (datetime.time(15, 30), '15:30'), (datetime.time(10, 0), '10:00'), (datetime.time(16, 30), '16:30'), (datetime.time(15, 0), '15:00'), (datetime.time(11, 0), '11:00'), (datetime.time(14, 30), '14:30')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'time'),
                'unique_together': {('patient', 'doctor', 'date', 'time')},
            },
        ),
    ]
